### ISSUE TITLE
Adicionar pacotes no arquivo tese.tex

### ISSUE THREAD

**Issue by mlimeira** [mlimeira/template-latex-ppgcc-ufac#13]
%--- fluxogramas
\usepackage{fancybox}
\usepackage{tikz}
\usetikzlibrary{shapes,arrows,calc}
%--- equações
\usepackage{mathtools}
\usepackage{array}
\usepackage{calc}
%--- links cruzados
\usepackage[hidelinks]{hyperref}

**Comment by mlimeira** [comment]
@thalescms

**Comment by thalescms** [comment]
Pacotes foram adicionados favor verificar

**Comment by mlimeira** [comment]
@thalescms aceita o convite para ser colaborador do projeto.

**Comment by thalescms** [comment]
Fechando o issues 14 Fix #13
