### ISSUE TITLE
Alterar a Figura 1 para o brasão da UFAC

### ISSUE THREAD

**Issue by mlimeira** [mlimeira/template-latex-ppgcc-ufac#2]

**Comment by danielnsilva** [comment]
@mlimeira se adicionar `\usepackage{epstopdf}` no arquivo tese.tex as figuras não são exibidas, porém o código é compilado sem erros.

**Comment by mlimeira** [comment]
@danielnsilva 
Faz um teste com essa configuração de pacotes para figuras.

%--- pacotes para figuras 
\usepackage{epsf}
\usepackage{epsfig,graphicx}
\usepackage{subfigure}
\usepackage{epstopdf}

**Comment by mlimeira** [comment]
:+1:
