### ISSUE TITLE
Adicionar parágrafos na seção de introdução.

### ISSUE THREAD

**Issue by mlimeira** [mlimeira/template-latex-ppgcc-ufac#4]
Os textos devem usar citações reais com as devidas referências adicionadas no arquivo bibliografia.bib

**Comment by mlimeira** [comment]
@silvana21

**Comment by mlimeira** [comment]
@silvana21 aceita o convite de colaborador para vc participar das revisões dos pull requests.

**Comment by silvana21** [comment]
Issue resolvida por pull request.
